### ISSUE TITLE
unable to build docker image

### ISSUE THREAD

**Issue by LUC4R4T0R** [opencrx/opencrx-docker#4]
I am unable to build the docker image with the given Dockerfile, because there seems to be a bug in apache's configuration:

![grafik](https://user-images.githubusercontent.com/26312201/172575240-bc44b73f-43f9-47db-b84c-940f841d0a0d.png)

**Comment by wfro64** [comment]
Thank you for the analysis. The cause of the problem is the use of different Ubuntu versions. To avoid problems of this kind in the future, ubuntu:latest is now used, i.e. "latest LTS".
